let content = document.querySelector('.js-generated.content')
let header = document.createElement('h1')
header.setAttribute('class', 'dog-name')
header.append('Rizzo')
let dogImage = document.createElement(img)
dogImage.setAttribute('src', './assets/rizzo.jpg')
dogImage.setAttribute('alt', 'Dog pic')
let container = document.createElement('.dog-content')
container.append(dogImage)
let para = document.createElement('p')
para.style.textAlign('center')
content.append(header)
